// Minimal embeddable widget script served by backend.
// Usage (generated by admin panel):
//   <script src="https://YOUR_BACKEND/widget.js" data-wl-chatbot-id="12345678" data-wl-integration-secret="..."></script>
// If you host widget.js as a downloaded file (file://) or from a different domain than the API, set the API host explicitly:
//   data-wl-api-origin="https://YOUR_BACKEND"   (no trailing slash; /api is added automatically)

;(function () {
  function getScriptEl() {
    const scripts = document.querySelectorAll('script[data-wl-chatbot-id][data-wl-integration-secret]')
    return scripts.length ? scripts[scripts.length - 1] : document.currentScript
  }

  function getConfig() {
    const el = getScriptEl() || null
    const chatbotId = el?.getAttribute?.('data-wl-chatbot-id') || ''
    const integrationSecret = el?.getAttribute?.('data-wl-integration-secret') || ''
    return { el, chatbotId: String(chatbotId), integrationSecret: String(integrationSecret) }
  }

  /**
   * @param {Element | null} scriptEl
   * @returns {string} API root including /api (e.g. https://x.com/api)
   */
  function resolveApiRoot(scriptEl) {
    const explicit =
      (scriptEl && scriptEl.getAttribute && scriptEl.getAttribute('data-wl-api-origin')) ||
      (scriptEl && scriptEl.getAttribute && scriptEl.getAttribute('data-wl-api-base')) ||
      ''
    const raw = String(explicit || '')
      .trim()
      .replace(/\/$/, '')
    if (raw) {
      const lower = raw.toLowerCase()
      if (lower.endsWith('/api')) return raw
      return `${raw}/api`
    }
    const src =
      document.currentScript?.getAttribute?.('src') ||
      Array.from(document.scripts || []).find((s) => /\/widget\.js(\?|$)/.test(s.src || ''))?.src ||
      ''
    try {
      const u = new URL(src)
      if (u.protocol === 'http:' || u.protocol === 'https:') {
        return `${u.origin}/api`
      }
    } catch {
      /* ignore */
    }
    return '/api'
  }

  const config = getConfig()
  const API_ROOT = resolveApiRoot(config.el)

  if (!config.chatbotId || !config.integrationSecret) return

  const ROOT_ID = `wl-chatbot-root-${config.chatbotId}`
  if (document.getElementById(ROOT_ID)) return

  const root = document.createElement('div')
  root.id = ROOT_ID
  document.body.appendChild(root)

  const styles = document.createElement('style')
  styles.textContent = `
    #${ROOT_ID} { all: initial; font-family: Arial, Helvetica, sans-serif; position: fixed; right: 16px; bottom: 16px; z-index: 999999; }
    #${ROOT_ID} * { box-sizing: border-box; }
    .wl-launcher { width: 54px; height: 54px; border-radius: 999px; border: 0; cursor: pointer; background: var(--wl-accent, #dc2626); color: #fff; display:flex; align-items:center; justify-content:center; font-size: 22px; box-shadow: 0 10px 28px rgba(0,0,0,.18); }
    .wl-panel { width: 350px; max-width: calc(100vw - 32px); background: #fff; border-radius: 14px; overflow:hidden; box-shadow: 0 18px 50px rgba(0,0,0,.22); border: 1px solid rgba(0,0,0,.12); position: absolute; right: 0; bottom: 68px; }
    .wl-head { background: var(--wl-header-bg, #111); color: var(--wl-header-text, #fff); padding: 12px 12px; display:flex; align-items:center; justify-content: space-between; gap: 8px; }
    .wl-bot { font-weight: 700; font-size: 14px; line-height: 1.2; }
    .wl-trial { font-size: 11px; opacity: .9; white-space: nowrap; overflow:hidden; text-overflow: ellipsis; }
    .wl-actions { display:flex; gap: 8px; }
    .wl-iconbtn { background: transparent; border: 0; color: inherit; cursor: pointer; padding: 6px 8px; border-radius: 8px; }
    .wl-body { padding: 12px; max-height: 360px; overflow:auto; background: var(--wl-surface, #fff); }
    .wl-msg { margin: 8px 0; display:flex; }
    .wl-msg--user { justify-content: flex-end; }
    .wl-bubble { padding: 10px 12px; border-radius: 12px; max-width: 84%; white-space: pre-wrap; word-break: break-word; font-size: 13px; line-height: 1.35; }
    .wl-bubble--user { background: var(--wl-user-bubble, #fee2e2); color: #111; border: 1px solid rgba(0,0,0,.06); }
    .wl-bubble--bot { background: var(--wl-bot-bubble, #fff); color: #111; border: 1px solid rgba(0,0,0,.08); }
    .wl-foot { border-top: 1px solid rgba(0,0,0,.08); padding: 10px; display:flex; gap: 8px; background: #fff; }
    .wl-input { flex:1; border: 1px solid rgba(0,0,0,.16); border-radius: 10px; padding: 10px 10px; outline: none; font-size: 13px; }
    .wl-send { border:0; border-radius: 10px; background: var(--wl-accent, #dc2626); color:#fff; cursor:pointer; padding: 10px 12px; font-weight: 700; }
    .wl-disclaimer { font-size: 11px; opacity: .8; margin-top: 6px; }
    .wl-error { background: #fef2f2; color: #991b1b; padding: 10px; border-radius: 10px; border: 1px solid rgba(153,27,27,.25); font-size: 12px; margin-bottom: 8px; }
    .wl-contact { background: #fff7ed; color: #7c2d12; padding: 10px; border-radius: 10px; border: 1px solid rgba(194,65,12,.25); font-size: 12px; margin-bottom: 8px; line-height: 1.45; }
    .wl-contact b { display: inline-block; min-width: 56px; }
    .wl-contact a { color: inherit; text-decoration: underline; }
    .wl-loading { opacity: .7; font-size: 12px; margin-top: 8px; }
    .wl-lead { display: flex; flex-direction: column; gap: 8px; margin-top: 6px; }
    .wl-lead-label { display: flex; flex-direction: column; gap: 4px; font-size: 11px; font-weight: 700; color: #374151; }
    .wl-lead-input { border: 1px solid rgba(0,0,0,.16); border-radius: 8px; padding: 8px; font-size: 13px; width: 100%; }
    .wl-lead-submit { margin-top: 6px; border: 0; border-radius: 10px; background: var(--wl-accent, #dc2626); color: #fff; padding: 10px; font-weight: 700; cursor: pointer; font-size: 13px; }
    .wl-lead-submit:disabled { opacity: .65; cursor: not-allowed; }
  `
  document.head.appendChild(styles)

  let panelOpen = false
  let sending = false

  let sessionId = ''
  let threadId = ''
  let allHistory = []
  let theme = null
  let trialEndsAtIso = ''
  let trialExpired = false
  let supportContact = null
  let leadCaptured = false
  let leadSubmitting = false

  const errorState = { message: '' }
  const leadGateError = { message: '' }

  function setVarsFromTheme(t) {
    if (!t || !t.colors) return
    root.style.setProperty('--wl-accent', t.colors.accentSoft || t.colors.accent || '#dc2626')
    root.style.setProperty('--wl-header-bg', t.colors.headerBg || '#111')
    root.style.setProperty('--wl-header-text', t.colors.headerText || '#fff')
    root.style.setProperty('--wl-surface', t.colors.surface || '#fff')
    root.style.setProperty('--wl-user-bubble', t.colors.userBubble || '#fee2e2')
    root.style.setProperty('--wl-bot-bubble', t.colors.botBubble || '#fff')
  }

  function formatTrial(trialEndsAt) {
    if (!trialEndsAt) return ''
    const end = Date.parse(trialEndsAt)
    if (!Number.isFinite(end)) return ''
    const diff = end - Date.now()
    if (diff <= 0) return 'Trial ended'
    const mins = Math.floor(diff / 60000)
    if (mins < 60) return `Trial ends in ~${mins}m`
    const hours = Math.floor(mins / 60)
    return `Trial ends in ~${hours}h`
  }

  function render() {
    root.innerHTML = ''
    if (!panelOpen) {
      const launcher = document.createElement('button')
      launcher.className = 'wl-launcher'
      launcher.type = 'button'
      launcher.textContent = 'Chat'
      launcher.addEventListener('click', () => {
        panelOpen = true
        render()
        ensureOpened().catch(() => {})
      })
      root.appendChild(launcher)
      return
    }

    const panel = document.createElement('div')
    panel.className = 'wl-panel'

    const head = document.createElement('div')
    head.className = 'wl-head'
    const bot = document.createElement('div')
    bot.className = 'wl-bot'
    bot.textContent = (theme && theme.chatbotName) ? theme.chatbotName : 'Chatbot'

    const trial = document.createElement('div')
    trial.className = 'wl-trial'
    trial.textContent = trialExpired ? 'Trial ended' : formatTrial(trialEndsAtIso)

    const actions = document.createElement('div')
    actions.className = 'wl-actions'

    const signout = document.createElement('button')
    signout.type = 'button'
    signout.className = 'wl-iconbtn'
    signout.textContent = 'Reset'
    signout.addEventListener('click', () => {
      panelOpen = false
      sessionId = ''
      threadId = ''
      allHistory = []
      trialExpired = false
      trialEndsAtIso = ''
      theme = null
      supportContact = null
      leadCaptured = false
      leadSubmitting = false
      leadGateError.message = ''
      errorState.message = ''
      render()
    })

    actions.appendChild(signout)
    head.appendChild(bot)
    head.appendChild(trial)
    head.appendChild(actions)

    const body = document.createElement('div')
    body.className = 'wl-body'

    if (errorState.message) {
      const err = document.createElement('div')
      err.className = 'wl-error'
      err.textContent = errorState.message
      body.appendChild(err)
    }

    const waitingForSession = !sessionId && !errorState.message
    const showLeadGate = sessionId && !trialExpired && !leadCaptured

    if (waitingForSession) {
      const load = document.createElement('div')
      load.className = 'wl-disclaimer'
      load.textContent = 'Opening chat…'
      body.appendChild(load)
      panel.appendChild(head)
      panel.appendChild(body)
      root.appendChild(panel)
      return
    }

    if (showLeadGate) {
      const intro = document.createElement('div')
      intro.className = 'wl-disclaimer'
      intro.textContent = 'Share your name, email, and phone to start. The business receives this as a lead.'
      body.appendChild(intro)
      if (leadGateError.message) {
        const lerr = document.createElement('div')
        lerr.className = 'wl-error'
        lerr.textContent = leadGateError.message
        body.appendChild(lerr)
      }
      const form = document.createElement('form')
      form.className = 'wl-lead'
      function labeledInput(labelText, name, type, autocomp) {
        const lab = document.createElement('label')
        lab.className = 'wl-lead-label'
        lab.textContent = labelText
        const inp = document.createElement('input')
        inp.className = 'wl-lead-input'
        inp.name = name
        inp.type = type || 'text'
        if (autocomp) inp.setAttribute('autocomplete', autocomp)
        lab.appendChild(inp)
        form.appendChild(lab)
        return inp
      }
      const inName = labeledInput('Name *', 'name', 'text', 'name')
      const inEmail = labeledInput('Email *', 'email', 'email', 'email')
      const inPhone = labeledInput('Phone *', 'phone', 'tel', 'tel')
      const btn = document.createElement('button')
      btn.type = 'submit'
      btn.className = 'wl-lead-submit'
      btn.textContent = leadSubmitting ? 'Saving…' : 'Continue to chat'
      btn.disabled = leadSubmitting
      form.appendChild(btn)
      form.addEventListener('submit', (e) => {
        e.preventDefault()
        const nm = String(inName.value || '').trim()
        const em = String(inEmail.value || '').trim()
        const ph = String(inPhone.value || '').trim()
        leadGateError.message = ''
        if (!nm) {
          leadGateError.message = 'Name is required.'
          render()
          return
        }
        if (!em || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(em)) {
          leadGateError.message = 'Valid email is required.'
          render()
          return
        }
        if (!ph) {
          leadGateError.message = 'Phone is required.'
          render()
          return
        }
        leadSubmitting = true
        render()
        fetch(`${API_ROOT}/chatbot-test/session-lead`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ sessionId, name: nm, email: em, phone: ph }),
        })
          .then((r) => r.json().then((d) => ({ r, d })))
          .then(({ r, d }) => {
            leadSubmitting = false
            if (!r.ok || !d.ok) {
              leadGateError.message = typeof d.error === 'string' && d.error.trim() ? d.error.trim() : 'Could not save.'
              render()
              return
            }
            leadCaptured = true
            leadGateError.message = ''
            render()
          })
          .catch(() => {
            leadSubmitting = false
            leadGateError.message = 'Network error. Try again.'
            render()
          })
      })
      body.appendChild(form)
      panel.appendChild(head)
      panel.appendChild(body)
      root.appendChild(panel)
      return
    }

    if (!sessionId) {
      panel.appendChild(head)
      panel.appendChild(body)
      root.appendChild(panel)
      return
    }

    // Contact details are intentionally not shown inside chatbot UI.

    const currentThreadMessages = (allHistory || []).filter((m) => String(m.threadId || '') === String(threadId || ''))
    if (!currentThreadMessages.length) {
      const empty = document.createElement('div')
      empty.className = 'wl-disclaimer'
      empty.textContent = 'Ask anything. Answers come from your scraped website content.'
      body.appendChild(empty)
    } else {
      currentThreadMessages.forEach((m) => {
        const row = document.createElement('div')
        row.className = `wl-msg ${m.role === 'user' ? 'wl-msg--user' : ''}`
        const bubble = document.createElement('div')
        bubble.className = `wl-bubble ${m.role === 'user' ? 'wl-bubble--user' : 'wl-bubble--bot'}`
        bubble.textContent = m.content || ''
        row.appendChild(bubble)
        body.appendChild(row)
      })
    }

    const loading = document.createElement('div')
    loading.className = 'wl-loading'
    loading.textContent = sending ? 'Sending…' : ''
    body.appendChild(loading)

    const foot = document.createElement('div')
    foot.className = 'wl-foot'

    const input = document.createElement('input')
    input.className = 'wl-input'
    input.placeholder = 'Type your question...'
    input.value = ''

    const send = document.createElement('button')
    send.className = 'wl-send'
    send.type = 'button'
    send.textContent = 'Send'

    const onSend = () => {
      const text = String(input.value || '').trim()
      if (!text || sending || trialExpired) return
      if (!leadCaptured) {
        errorState.message = 'Complete the contact form above first.'
        render()
        return
      }
      input.value = ''
      sending = true
      ensureMessage(text).finally(() => {
        sending = false
        render()
      })
      render()
    }

    send.addEventListener('click', onSend)
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') onSend()
    })

    foot.appendChild(input)
    foot.appendChild(send)

    panel.appendChild(head)
    panel.appendChild(body)
    panel.appendChild(foot)
    root.appendChild(panel)
  }

  const SESSION_INVALID_RE = /session expired|session invalid|unlock again/i

  function isSessionInvalidResponse(res, data) {
    if (res.status === 401) return true
    const msg = typeof data?.error === 'string' ? data.error : ''
    return SESSION_INVALID_RE.test(msg)
  }

  async function ensureOpened(force = false) {
    if (!force && sessionId) return
    errorState.message = ''
    leadGateError.message = ''
    render()
    const res = await fetch(`${API_ROOT}/widget/open`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chatbotId: config.chatbotId, integrationSecret: config.integrationSecret }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok || !data.ok) {
      const apiErr = typeof data.error === 'string' && data.error.trim() ? data.error.trim() : 'Failed to open chatbot'
      if (res.status === 403 && data.trialExpired) {
        trialExpired = true
        trialEndsAtIso = data.trialEndsAt || ''
        errorState.message = apiErr
      } else {
        errorState.message = apiErr
      }
      render()
      throw new Error(apiErr)
    }

    sessionId = String(data.sessionId || '')
    threadId = String(data.threadId || '')
    allHistory = Array.isArray(data.chatHistory) ? data.chatHistory : []
    theme = data.theme || null
    setVarsFromTheme(theme)
    trialEndsAtIso = data.trialEndsAt || ''
    trialExpired = !!data.trialExpired
    supportContact = data.supportContact || null
    errorState.message = ''
    leadCaptured = false
    leadGateError.message = ''
    render()
  }

  async function postMessage(sessionIdValue, text) {
    const res = await fetch(`${API_ROOT}/chatbot-test/message`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId: sessionIdValue, message: text }),
    })
    const data = await res.json().catch(() => ({}))
    return { res, data }
  }

  async function ensureMessage(text) {
    if (!sessionId) {
      try {
        await ensureOpened()
      } catch {
        return
      }
    }
    if (!sessionId) return
    if (!trialExpired && !leadCaptured) {
      errorState.message = 'Add your name, email, and phone to start chatting.'
      render()
      return
    }
    errorState.message = ''

    // Optimistic echo
    const nowIso = new Date().toISOString()
    const optimisticId = `opt-u-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`
    allHistory = (allHistory || []).concat([{ id: optimisticId, threadId, role: 'user', content: text, createdAt: nowIso }])
    render()

    let { res, data } = await postMessage(sessionId, text)

    // Session may expire after idle/refresh; auto-open fresh session and retry once.
    if (isSessionInvalidResponse(res, data)) {
      try {
        await ensureOpened(true)
      } catch {
        // keep original response handling below
      }
      if (sessionId) {
        const retry = await postMessage(sessionId, text)
        res = retry.res
        data = retry.data
      }
    }

    if (res.status === 403 && data.trialExpired) {
      trialExpired = true
      errorState.message = 'Trial ended. Contact the business to continue.'
      render()
      return
    }
    if (res.status === 428 && data.needLead) {
      leadCaptured = false
      errorState.message =
        typeof data.error === 'string' && data.error.trim() ? data.error.trim() : 'Complete the contact form first.'
      allHistory = (allHistory || []).filter((m) => !(m && String(m.id || '') === optimisticId))
      render()
      return
    }
    if (!res.ok || !data.ok) {
      const apiErr = typeof data.error === 'string' && data.error.trim() ? data.error.trim() : 'Message failed'
      errorState.message = apiErr
      // Remove optimistic user message if server failed.
      allHistory = (allHistory || []).filter((m) => !(m && String(m.id || '') === optimisticId))
      render()
      return
    }

    const reply = typeof data.reply === 'string' ? data.reply : ''
    if (reply) {
      allHistory = allHistory.concat([{ id: `opt-a-${nowIso}`, threadId: threadId, role: 'assistant', content: reply, createdAt: new Date().toISOString() }])
    }
    render()
  }

  render()
})()

