// Minimal embeddable widget script served by backend.
// Usage (generated by admin panel):
//   <script src="https://YOUR_BACKEND/widget.js" data-wl-chatbot-id="12345678" data-wl-integration-secret="..."></script>

;(function () {
  function getConfig() {
    const scripts = document.querySelectorAll('script[data-wl-chatbot-id][data-wl-integration-secret]')
    const cfgEl = scripts.length ? scripts[scripts.length - 1] : (document.currentScript || null)
    const el = cfgEl || null
    const chatbotId = el?.getAttribute?.('data-wl-chatbot-id') || ''
    const integrationSecret = el?.getAttribute?.('data-wl-integration-secret') || ''
    return { chatbotId: String(chatbotId), integrationSecret: String(integrationSecret) }
  }

  function inferOriginFromScript() {
    const src =
      document.currentScript?.getAttribute?.('src') ||
      Array.from(document.scripts || []).find((s) => /\/widget\.js(\?|$)/.test(s.src || ''))?.src ||
      ''
    try {
      const u = new URL(src)
      return u.origin
    } catch {
      return ''
    }
  }

  const config = getConfig()
  const ORIGIN = inferOriginFromScript()
  const API_ROOT = ORIGIN ? `${ORIGIN}/api` : '/api'

  if (!config.chatbotId || !config.integrationSecret) return

  const ROOT_ID = `wl-chatbot-root-${config.chatbotId}`
  if (document.getElementById(ROOT_ID)) return

  const root = document.createElement('div')
  root.id = ROOT_ID
  document.body.appendChild(root)

  const styles = document.createElement('style')
  styles.textContent = `
    #${ROOT_ID} { all: initial; font-family: Arial, Helvetica, sans-serif; position: fixed; right: 16px; bottom: 16px; z-index: 999999; }
    #${ROOT_ID} * { box-sizing: border-box; }
    .wl-launcher { width: 54px; height: 54px; border-radius: 999px; border: 0; cursor: pointer; background: var(--wl-accent, #dc2626); color: #fff; display:flex; align-items:center; justify-content:center; font-size: 22px; box-shadow: 0 10px 28px rgba(0,0,0,.18); }
    .wl-panel { width: 350px; max-width: calc(100vw - 32px); background: #fff; border-radius: 14px; overflow:hidden; box-shadow: 0 18px 50px rgba(0,0,0,.22); border: 1px solid rgba(0,0,0,.12); position: absolute; right: 0; bottom: 68px; }
    .wl-head { background: var(--wl-header-bg, #111); color: var(--wl-header-text, #fff); padding: 12px 12px; display:flex; align-items:center; justify-content: space-between; gap: 8px; }
    .wl-bot { font-weight: 700; font-size: 14px; line-height: 1.2; }
    .wl-trial { font-size: 11px; opacity: .9; white-space: nowrap; overflow:hidden; text-overflow: ellipsis; }
    .wl-actions { display:flex; gap: 8px; }
    .wl-iconbtn { background: transparent; border: 0; color: inherit; cursor: pointer; padding: 6px 8px; border-radius: 8px; }
    .wl-body { padding: 12px; max-height: 360px; overflow:auto; background: var(--wl-surface, #fff); }
    .wl-msg { margin: 8px 0; display:flex; }
    .wl-msg--user { justify-content: flex-end; }
    .wl-bubble { padding: 10px 12px; border-radius: 12px; max-width: 84%; white-space: pre-wrap; word-break: break-word; font-size: 13px; line-height: 1.35; }
    .wl-bubble--user { background: var(--wl-user-bubble, #fee2e2); color: #111; border: 1px solid rgba(0,0,0,.06); }
    .wl-bubble--bot { background: var(--wl-bot-bubble, #fff); color: #111; border: 1px solid rgba(0,0,0,.08); }
    .wl-foot { border-top: 1px solid rgba(0,0,0,.08); padding: 10px; display:flex; gap: 8px; background: #fff; }
    .wl-input { flex:1; border: 1px solid rgba(0,0,0,.16); border-radius: 10px; padding: 10px 10px; outline: none; font-size: 13px; }
    .wl-send { border:0; border-radius: 10px; background: var(--wl-accent, #dc2626); color:#fff; cursor:pointer; padding: 10px 12px; font-weight: 700; }
    .wl-disclaimer { font-size: 11px; opacity: .8; margin-top: 6px; }
    .wl-error { background: #fef2f2; color: #991b1b; padding: 10px; border-radius: 10px; border: 1px solid rgba(153,27,27,.25); font-size: 12px; margin-bottom: 8px; }
    .wl-loading { opacity: .7; font-size: 12px; margin-top: 8px; }
  `
  document.head.appendChild(styles)

  let panelOpen = false
  let sending = false

  let sessionId = ''
  let threadId = ''
  let allHistory = []
  let theme = null
  let trialEndsAtIso = ''
  let trialExpired = false
  let companyContact = null

  function setVarsFromTheme(t) {
    if (!t || !t.colors) return
    root.style.setProperty('--wl-accent', t.colors.accentSoft || t.colors.accent || '#dc2626')
    root.style.setProperty('--wl-header-bg', t.colors.headerBg || '#111')
    root.style.setProperty('--wl-header-text', t.colors.headerText || '#fff')
    root.style.setProperty('--wl-surface', t.colors.surface || '#fff')
    root.style.setProperty('--wl-user-bubble', t.colors.userBubble || '#fee2e2')
    root.style.setProperty('--wl-bot-bubble', t.colors.botBubble || '#fff')
  }

  function formatTrial(trialEndsAt) {
    if (!trialEndsAt) return ''
    const end = Date.parse(trialEndsAt)
    if (!Number.isFinite(end)) return ''
    const diff = end - Date.now()
    if (diff <= 0) return 'Trial ended'
    const mins = Math.floor(diff / 60000)
    if (mins < 60) return `Trial ends in ~${mins}m`
    const hours = Math.floor(mins / 60)
    return `Trial ends in ~${hours}h`
  }

  function render() {
    root.innerHTML = ''
    if (!panelOpen) {
      const launcher = document.createElement('button')
      launcher.className = 'wl-launcher'
      launcher.type = 'button'
      launcher.textContent = 'Chat'
      launcher.addEventListener('click', () => {
        panelOpen = true
        render()
        ensureOpened().catch(() => {})
      })
      root.appendChild(launcher)
      return
    }

    const panel = document.createElement('div')
    panel.className = 'wl-panel'

    const head = document.createElement('div')
    head.className = 'wl-head'
    const bot = document.createElement('div')
    bot.className = 'wl-bot'
    bot.textContent = (theme && theme.chatbotName) ? theme.chatbotName : 'Chatbot'

    const trial = document.createElement('div')
    trial.className = 'wl-trial'
    trial.textContent = trialExpired ? 'Trial ended' : formatTrial(trialEndsAtIso)

    const actions = document.createElement('div')
    actions.className = 'wl-actions'

    const signout = document.createElement('button')
    signout.type = 'button'
    signout.className = 'wl-iconbtn'
    signout.textContent = 'Reset'
    signout.addEventListener('click', () => {
      panelOpen = false
      sessionId = ''
      threadId = ''
      allHistory = []
      trialExpired = false
      trialEndsAtIso = ''
      theme = null
      companyContact = null
      render()
    })

    actions.appendChild(signout)
    head.appendChild(bot)
    head.appendChild(trial)
    head.appendChild(actions)

    const body = document.createElement('div')
    body.className = 'wl-body'

    if (errorState.message) {
      const err = document.createElement('div')
      err.className = 'wl-error'
      err.textContent = errorState.message
      body.appendChild(err)
    }

    const currentThreadMessages = (allHistory || []).filter((m) => String(m.threadId || '') === String(threadId || ''))
    if (!currentThreadMessages.length) {
      const empty = document.createElement('div')
      empty.className = 'wl-disclaimer'
      empty.textContent = 'Ask anything. Answers come from your scraped website content.'
      body.appendChild(empty)
    } else {
      currentThreadMessages.forEach((m) => {
        const row = document.createElement('div')
        row.className = `wl-msg ${m.role === 'user' ? 'wl-msg--user' : ''}`
        const bubble = document.createElement('div')
        bubble.className = `wl-bubble ${m.role === 'user' ? 'wl-bubble--user' : 'wl-bubble--bot'}`
        bubble.textContent = m.content || ''
        row.appendChild(bubble)
        body.appendChild(row)
      })
    }

    const loading = document.createElement('div')
    loading.className = 'wl-loading'
    loading.textContent = sending ? 'Sending…' : ''
    body.appendChild(loading)

    const foot = document.createElement('div')
    foot.className = 'wl-foot'

    const input = document.createElement('input')
    input.className = 'wl-input'
    input.placeholder = 'Type your question...'
    input.value = ''

    const send = document.createElement('button')
    send.className = 'wl-send'
    send.type = 'button'
    send.textContent = 'Send'

    const onSend = () => {
      const text = String(input.value || '').trim()
      if (!text || sending || trialExpired) return
      input.value = ''
      sending = true
      ensureMessage(text).finally(() => {
        sending = false
        render()
      })
      render()
    }

    send.addEventListener('click', onSend)
    input.addEventListener('keydown', (e) => {
      if (e.key === 'Enter') onSend()
    })

    foot.appendChild(input)
    foot.appendChild(send)

    panel.appendChild(head)
    panel.appendChild(body)
    panel.appendChild(foot)
    root.appendChild(panel)
  }

  const errorState = { message: '' }

  async function ensureOpened() {
    if (sessionId) return
    errorState.message = ''
    render()
    const res = await fetch(`${API_ROOT}/widget/open`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ chatbotId: config.chatbotId, integrationSecret: config.integrationSecret }),
    })
    const data = await res.json().catch(() => ({}))
    if (!res.ok || !data.ok) {
      const apiErr = typeof data.error === 'string' && data.error.trim() ? data.error.trim() : 'Failed to open chatbot'
      if (res.status === 403 && data.trialExpired) {
        trialExpired = true
        trialEndsAtIso = data.trialEndsAt || ''
        errorState.message = apiErr
      } else {
        errorState.message = apiErr
      }
      render()
      throw new Error(apiErr)
    }

    sessionId = String(data.sessionId || '')
    threadId = String(data.threadId || '')
    allHistory = Array.isArray(data.chatHistory) ? data.chatHistory : []
    theme = data.theme || null
    setVarsFromTheme(theme)
    trialEndsAtIso = data.trialEndsAt || ''
    trialExpired = !!data.trialExpired
    companyContact = data.companyContact || null
    errorState.message = ''
    render()
  }

  async function ensureMessage(text) {
    if (!sessionId) return
    errorState.message = ''

    // Optimistic echo
    const nowIso = new Date().toISOString()
    allHistory = (allHistory || []).concat([{ id: `opt-u-${nowIso}`, threadId, role: 'user', content: text, createdAt: nowIso }])
    render()

    const res = await fetch(`${API_ROOT}/chatbot-test/message`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId, message: text, tone: 'professional' }),
    })
    const data = await res.json().catch(() => ({}))
    if (res.status === 403 && data.trialExpired) {
      trialExpired = true
      errorState.message = 'Trial ended. Contact the business to continue.'
      render()
      return
    }
    if (!res.ok || !data.ok) {
      const apiErr = typeof data.error === 'string' && data.error.trim() ? data.error.trim() : 'Message failed'
      errorState.message = apiErr
      // Remove optimistic user message if server failed.
      allHistory = (allHistory || []).filter((m) => !(m && String(m.id || '').startsWith('opt-u-') && m.role === 'user' && String(m.createdAt || '').includes(nowIso.slice(0, 10))))
      render()
      return
    }

    const reply = typeof data.reply === 'string' ? data.reply : ''
    if (reply) {
      allHistory = allHistory.concat([{ id: `opt-a-${nowIso}`, threadId: threadId, role: 'assistant', content: reply, createdAt: new Date().toISOString() }])
    }
    render()
  }

  render()
})()

